In [1]:
import numpy as np

In [2]:
tyy = np.array([[3,7,9],[4,8,6]])
print(tyy)

[[3 7 9]
 [4 8 6]]


In [4]:
print(tyy.shape)

(2, 3)


In [5]:
print(tyy.reshape(3,2))

[[3 7]
 [9 4]
 [8 6]]


In [6]:
print(tyy)

[[3 7 9]
 [4 8 6]]


In [7]:
print(tyy.reshape(6,1))

[[3]
 [7]
 [9]
 [4]
 [8]
 [6]]


In [8]:
print(tyy.reshape(1,6))

[[3 7 9 4 8 6]]


In [9]:
print(tyy*3)

[[ 9 21 27]
 [12 24 18]]


In [10]:
gh = np.array([2,9,6,4])
t = gh.copy()

In [11]:
gh

array([2, 9, 6, 4])

In [12]:
t

array([2, 9, 6, 4])

In [13]:
t[2] = 3

In [14]:
gh

array([2, 9, 6, 4])

In [15]:
t

array([2, 9, 3, 4])

In [16]:
gh_2 = np.array([7,2,6,4])
t_2 = gh_2.view()

In [17]:
gh_2

array([7, 2, 6, 4])

In [18]:
t_2

array([7, 2, 6, 4])

In [19]:
t_2[1] = 3

In [20]:
gh_2

array([7, 3, 6, 4])

In [21]:
t_2

array([7, 3, 6, 4])

In [22]:
vc = np.array([3,5,6,7])
print(vc)
print(vc.shape)

[3 5 6 7]
(4,)


In [23]:
vcx = np.array([6,7,2,9], ndmin = 5)
print(vcx)
print(vcx.shape)

[[[[[6 7 2 9]]]]]
(1, 1, 1, 1, 4)


In [24]:
print(vcx.ndim)

5


In [25]:
print(gh.ndim)

1


In [26]:
print(tyy.ndim)

2


In [27]:
jk = np.array([6,1,9,3,7])

In [29]:
jk = np.array([6,1,9,3,7], ndmin = 8)

In [30]:
print(jk.shape)

(1, 1, 1, 1, 1, 1, 1, 5)


In [31]:
ad = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [38]:
print(ad)
print()
print(ad.reshape(4,3))
print()
print(ad.reshape(3,4))
print()
print(ad.reshape(6,2))
print()
print(ad.reshape(2,6))
print()
print(ad.reshape(12,1))
print()


[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]



In [41]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr)
print()

for x in arr:
    print(x)
    
print()

for x in arr:
    for y in x:
        print(y)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [50]:
for k in range(1,10,2):
    print(k)

1
3
5
7
9
