In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [3]:
print(np.__version__)

1.21.5


## NumPy Creating Arrays

In [4]:
arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr = np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


## Dimensions In Arrays

### 0 - D Arrays

In [6]:
arr = np.array(43)

print(arr)

43


### 1 - D Arrays

In [7]:
arr = np.array([2,3,6,8])

print(arr)

[2 3 6 8]


### 2 - D Arrays

In [8]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 3 - D Arrays

In [19]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])

print(arr)

print("Number Of Dimensions:",arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]
Number Of Dimensions: 3


In [20]:
arr = np.array([[[9,8,7],[6,5,4],[3,2,1]]])

print(arr)
print("Number of Dimensions:",arr.ndim)

[[[9 8 7]
  [6 5 4]
  [3 2 1]]]
Number of Dimensions: 3


In [23]:
ass = np.array([[[5,2,6],[1,8,9],[3,9,7]]], ndmin = 5)

print(ass)
print("Number Of Dimensions:",ass.ndim)

[[[[[5 2 6]
    [1 8 9]
    [3 9 7]]]]]
Number Of Dimensions: 5


## Check Number Of Dimensions

In [25]:
a = np.array(64)
b = np.array([2,3,6,7])
c = np.array([[3,6,8],[7,4,1]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,2,1]]])
e = np.array([[3,6,8],[7,4,1]], ndmin = 5)

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
5


## Higher Dimensional Arrays

In [27]:
arr = np.array([1,2,3,4,5], ndmin = 5)

print(arr)
print("Number Of Dimensions:",arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number Of Dimensions: 5


## NumPy Array Indexing

In [29]:
arr = np.array([1,2,3,4,5])

print(arr[2])

3


In [30]:
arr = np.array([1,2,3,4,5])

print(arr[1] + arr[3])

6


In [31]:
arr = np.array([1,2,3,4,5])

print(arr[1] * arr[3])

8


### Access 2 - D Arrays

In [32]:
arr = np.array([[1,2,3,4],[9,8,7,6]])

print('3rd Element Of 2nd Row:', arr[1,2])

3rd Element Of 2nd Row: 7


In [34]:
arr = np.array([[1,2,3,4,7],[6,7,8,9,0]])

print('5th Element Of 1st Row:', arr[0,4])

5th Element Of 1st Row: 7


In [36]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0,1,2])

6


#### Example Explained
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

### Negative Indexing

In [38]:
arr = np.array([[1,4,5,6,7],[2,6,7,4,9]])

print('Last element of 2nd dim:' , arr[1,-1])

Last element of 2nd dim: 9


## NumPy Array Slicing

In [44]:
arr = np.array([2,4,1,4,6,9])

print(arr[2:5])

[1 4 6]


In [39]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [43]:
arr = np.array([1,2,3,4,5,8,7])

print(arr[:6])

[1 2 3 4 5 8]


### Negative Slicing

In [50]:
arr = np.array([9,8,7,6,5,4,3])

print(arr[-5:-2])

[7 6 5]


### Step

In [49]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[1:6:2])

[2 4 6]


In [54]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[::2])

[1 3 5 7]


In [55]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[::3])

[1 4 7]


### Slicing 2 - D Arrays