In [2]:
import numpy as np

In [2]:
arrt = np.array([3,7,9,4])
print(arrt)

[3 7 9 4]


In [3]:
type(arrt)

numpy.ndarray

In [4]:
arrt.ndim

1

In [5]:
arrt.shape

(4,)

In [4]:
arrt_2 = np.array([[3,7,1,6],[4,6,9,7]])
print(arrt_2)
print("Dimension: ", arrt_2.ndim)

[[3 7 1 6]
 [4 6 9 7]]
Dimension:  2


In [5]:
print(arrt_2.shape)

(2, 4)


In [13]:
arrt3 = np.array([[[3,6,7,4],[5,6,9,7]],[[5,7,1,6],[5,6,8,3]]])
print(arrt3)
print("Dimension: ",arrt3.ndim)
print("Shape: ",arrt3.shape)

[[[3 6 7 4]
  [5 6 9 7]]

 [[5 7 1 6]
  [5 6 8 3]]]
Dimension:  3
Shape:  (2, 2, 4)


In [20]:
arrt4 = np.array([[[6,4,7,2],[4,9,7,2]],[[6,8,2,1],[4,3,7,9]]],ndmin = 4)
print(arrt4)
print("Dimension: ",arrt4.ndim)
print("Shape: ",arrt4.shape)

[[[[6 4 7 2]
   [4 9 7 2]]

  [[6 8 2 1]
   [4 3 7 9]]]]
Dimension:  4
Shape:  (1, 2, 2, 4)


In [21]:
nm = np.array([4,7,3,5])
print(nm)

[4 7 3 5]


In [24]:
nm = np.array([6,7,3,9], ndmin = 3)
print(nm)

[[[6 7 3 9]]]


In [25]:
print(nm.shape)

(1, 1, 4)


In [27]:
rt = np.array([[1,6,4,2],[7,8,3]])
print(rt)

[list([1, 6, 4, 2]) list([7, 8, 3])]


C:\Users\Rutvi\AppData\Local\Temp\ipykernel_20720\3478528846.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  rt = np.array([[1,6,4,2],[7,8,3]])


In [28]:
type(rt)

numpy.ndarray

In [29]:
#Reshape
arrt_re = np.array([3,8,6,4])
print(arrt_re)

[3 8 6 4]


In [30]:
arrt_re_r = arrt_re.reshape(4,1)
print(arrt_re_r)

[[3]
 [8]
 [6]
 [4]]


In [31]:
arrt_re_r = arrt_re.reshape(2,2)
print(arrt_re_r)

[[3 8]
 [6 4]]


In [38]:
va = np.array([4,8,3,5])

sd = va * 3
print(sd)

[12 24  9 15]


In [39]:
vn = np.array([[3,6,7,9],[2,4,6,8]])
print(vn + 2)

[[ 5  8  9 11]
 [ 4  6  8 10]]


In [40]:
tyy = va * vn
print(tyy)

[[12 48 21 45]
 [ 8 32 18 40]]


In [41]:
print(np.add(sd,vn))

[[15 30 16 24]
 [14 28 15 23]]


In [42]:
print(np.multiply(sd,vn))

[[ 36 144  63 135]
 [ 24  96  54 120]]


In [43]:
nm_s = np.array([3,7,5,4])
print(nm_s)

[3 7 5 4]


In [44]:
print(nm_s.size)

4


In [46]:
bn_s = np.array([[9,4,6],[9,6,4]])
print(bn_s)
print()
print("ELEMENT SIZE: ",bn_s.size)

[[9 4 6]
 [9 6 4]]

ELEMENT SIZE:  6


In [3]:
rt = np.array([[2,5,7],[6,9,3]])
print(rt)

[[2 5 7]
 [6 9 3]]


In [6]:
print(rt.reshape(6,1))

[[2]
 [5]
 [7]
 [6]
 [9]
 [3]]


In [7]:
print(rt.reshape(3,2))

[[2 5]
 [7 6]
 [9 3]]


In [8]:
print(rt.reshape(2,3))

[[2 5 7]
 [6 9 3]]


In [13]:
print(1.0 + 2.0j)

(1+2j)
